// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/resident-community/ResidentApp.tsx": () => import("../components/mockups/resident-community/ResidentApp.tsx"),
  "./components/mockups/retro-chocolatier-hero/RetroChocolatierHomeScreenSharpened.tsx": () => import("../components/mockups/retro-chocolatier-hero/RetroChocolatierHomeScreenSharpened.tsx"),
  "./components/mockups/templates/RetroChocolatierHomeScreen-DXPTP2/App.tsx": () => import("../components/mockups/templates/RetroChocolatierHomeScreen-DXPTP2/App.tsx"),
  "./components/mockups/templates/CottagecoreInteriorHomeScreen-smHjrB/App.tsx": () => import("../components/mockups/templates/CottagecoreInteriorHomeScreen-smHjrB/App.tsx"),
  "./components/mockups/templates/RetroChocolatierHomeScreen-ifGQOh/App.tsx": () => import("../components/mockups/templates/RetroChocolatierHomeScreen-ifGQOh/App.tsx")
};
