import { useState, type ReactNode } from "react";
import "./_group.css";
import {
  ArrowLeft, ArrowRight, Bell, CalendarDays, Check, ChevronRight, Clock3,
  CreditCard, Download, Droplets, FileText, Home, Info, KeyRound, MapPin,
  Menu, MessageCircle, MoreHorizontal, Phone, QrCode, Receipt, Search,
  Send, Shield, ShoppingBag, Star, Tag, UserRound, Users, Wallet, Wrench,
  X, Zap, Car, CircleAlert, CircleCheck, CircleDollarSign, PackageCheck,
  Plus, Minus, Share2, Camera, SlidersHorizontal, Sparkles, Utensils, Heart
} from "lucide-react";

type Screen =
  | "home" | "visitors" | "community" | "payments" | "services"
  | "profile" | "notifications" | "login" | "otp" | "invite" | "pass"
  | "parking" | "kids" | "amenities" | "amenity-detail" | "booking-success"
  | "invoice" | "payment-method" | "payment-processing" | "payment-success"
  | "request" | "request-detail" | "request-success" | "workers" | "worker-detail"
  | "worker-request" | "marketplace" | "product" | "cart" | "checkout"
  | "orders" | "subscription" | "sos";

type IconType = typeof Home;

const visitors = [
  { name: "Ananya Mehta", relation: "Friend", date: "Today · 2:30 PM", status: "Current", color: "bg-rose-100 text-rose-700", initials: "AM" },
  { name: "Rohan Kapoor", relation: "Courier", date: "Tomorrow · 11:00 AM", status: "Upcoming", color: "bg-blue-100 text-blue-700", initials: "RK" },
  { name: "Meera & family", relation: "Family", date: "May 18 · 6:00 PM", status: "Completed", color: "bg-emerald-100 text-emerald-700", initials: "MF" },
  { name: "Arjun Nair", relation: "Guest", date: "May 11 · 8:00 PM", status: "Cancelled", color: "bg-slate-100 text-slate-600", initials: "AN" },
];

const requests = [
  { id: "SR-2841", title: "Water pressure in master bath", category: "Plumbing", status: "In progress", sla: "Technician by 4:00 PM", tone: "amber", updated: "Updated 34 min ago" },
  { id: "SR-2827", title: "Corridor light, Tower B · 7F", category: "Electrical", status: "Waiting", sla: "Parts being arranged", tone: "blue", updated: "Updated yesterday" },
  { id: "SR-2763", title: "AC filter replacement", category: "Maintenance", status: "Resolved", sla: "Closed May 12", tone: "green", updated: "Rated 5 stars" },
];

const vendors = [
  { name: "The Daily Basket", category: "Groceries", detail: "Farm-to-door pantry staples", color: "from-amber-100 to-orange-50", icon: ShoppingBag },
  { name: "Nourish Kitchen", category: "Meals", detail: "Fresh weekday lunches", color: "from-rose-100 to-amber-50", icon: Utensils },
  { name: "Paws & Whiskers", category: "Pet care", detail: "Trusted care at your doorstep", color: "from-blue-100 to-indigo-50", icon: Heart },
];

const amenities = [
  { name: "Sky Lounge", meta: "Tower A · Level 22", desc: "Sunset views, private dining and a quiet bar.", price: "₹1,200 / 2 hrs", icon: Sparkles, color: "bg-[#e4f0ef]" },
  { name: "The Club Pool", meta: "Clubhouse · Ground floor", desc: "Temperature-controlled pool with cabanas.", price: "Complimentary", icon: Droplets, color: "bg-[#e1eff7]" },
  { name: "Padel Court", meta: "Sports arena · Court 02", desc: "A fast, social game with equipment included.", price: "₹600 / hour", icon: Zap, color: "bg-[#f4ebc9]" },
];

const workers = [
  { name: "Ramesh Electric Works", service: "Electrician", rating: "4.9", jobs: "184 jobs", time: "Available today", initials: "RE", verified: true },
  { name: "Maya Home Studio", service: "Home cleaning", rating: "4.8", jobs: "96 jobs", time: "Next slot · tomorrow", initials: "MH", verified: true },
  { name: "Greenline Care", service: "Plant care", rating: "4.7", jobs: "61 jobs", time: "Available Saturday", initials: "GC", verified: true },
];

const products = [
  { name: "Alphonso mangoes · 2 kg", vendor: "The Daily Basket", price: 860, category: "Fresh picks", color: "bg-[#f8e3b2]", mark: "AM" },
  { name: "Five-day lunch plan", vendor: "Nourish Kitchen", price: 1450, category: "Meals", color: "bg-[#f5d8d3]", mark: "NK" },
  { name: "Balcony herb kit", vendor: "Leaf & Loam", price: 690, category: "Home", color: "bg-[#dce8d5]", mark: "LL" },
];

const nav = [
  { id: "home" as Screen, label: "Home", icon: Home },
  { id: "visitors" as Screen, label: "Visitors", icon: Users },
  { id: "community" as Screen, label: "Community", icon: MessageCircle },
  { id: "payments" as Screen, label: "Payments", icon: Wallet },
  { id: "services" as Screen, label: "Services", icon: Wrench },
];

function AppIcon({ icon: Icon, size = 20 }: { icon: IconType; size?: number }) {
  return <Icon size={size} strokeWidth={1.8} />;
}

export function ResidentApp() {
  const [screen, setScreen] = useState<Screen>("home");
  const [history, setHistory] = useState<Screen[]>([]);
  const [toast, setToast] = useState("");
  const [authenticated, setAuthenticated] = useState(true);
  const [selectedVisitor, setSelectedVisitor] = useState(visitors[0]);
  const [selectedAmenity, setSelectedAmenity] = useState(amenities[0]);
  const [selectedWorker, setSelectedWorker] = useState(workers[0]);
  const [selectedProduct, setSelectedProduct] = useState(products[0]);
  const [cartCount, setCartCount] = useState(0);
  const [paymentState, setPaymentState] = useState<"idle" | "processing" | "success">("idle");
  const [sosState, setSosState] = useState<"idle" | "confirm" | "active">("idle");

  const go = (next: Screen) => { setHistory((h) => [...h, screen]); setScreen(next); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const back = () => { const previous = history[history.length - 1]; if (previous) { setHistory(history.slice(0, -1)); setScreen(previous); } else setScreen("home"); };
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2600); };
  const navTo = (id: Screen) => { setHistory([]); setScreen(id); };

  if (!authenticated) return <LoginScreen onLogin={() => { setAuthenticated(true); setScreen("home"); }} />;

  const isRoot = nav.some((n) => n.id === screen);
  return (
    <div className="min-h-[100dvh] bg-[#f4f8f6] text-[#17333a] font-sans">
      <div className="mx-auto min-h-[100dvh] w-full max-w-[430px] overflow-hidden bg-[#f4f8f6] shadow-[0_0_50px_rgba(24,66,68,.08)]">
        {screen !== "sos" && <TopBar screen={screen} onBack={history.length ? back : undefined} onProfile={() => go("profile")} onNotifications={() => go("notifications")} isRoot={isRoot} />}
        <main className={screen === "sos" ? "" : "px-5 pb-28 pt-2"}>
          {screen === "home" && <HomeScreen go={go} notify={notify} />}
          {screen === "visitors" && <VisitorsScreen go={go} setSelected={setSelectedVisitor} notify={notify} />}
          {screen === "community" && <CommunityScreen go={go} setAmenity={setSelectedAmenity} setProduct={setSelectedProduct} notify={notify} />}
          {screen === "payments" && <PaymentsScreen go={go} notify={notify} />}
          {screen === "services" && <ServicesScreen go={go} setWorker={setSelectedWorker} notify={notify} />}
          {screen === "profile" && <ProfileScreen go={go} setAuthenticated={setAuthenticated} />}
          {screen === "notifications" && <NotificationsScreen go={go} notify={notify} />}
          {screen === "invite" && <InviteScreen onDone={() => { notify("Visitor invite sent to Ananya"); go("visitors"); }} />}
          {screen === "pass" && <PassScreen visitor={selectedVisitor} go={go} notify={notify} />}
          {screen === "parking" && <ParkingScreen notify={notify} />}
          {screen === "kids" && <KidsScreen notify={notify} />}
          {screen === "amenities" && <AmenitiesScreen go={go} setAmenity={setSelectedAmenity} />}
          {screen === "amenity-detail" && <AmenityDetail amenity={selectedAmenity} go={go} />}
          {screen === "booking-success" && <BookingSuccess go={go} />}
          {screen === "invoice" && <InvoiceScreen go={go} />}
          {screen === "payment-method" && <PaymentMethodScreen go={go} setPaymentState={setPaymentState} />}
          {screen === "payment-processing" && <PaymentProcessing go={go} setPaymentState={setPaymentState} />}
          {screen === "payment-success" && <PaymentSuccess go={go} />}
          {screen === "request" && <RequestForm onDone={() => { notify("Request SR-2847 raised"); go("services"); }} />}
          {screen === "request-detail" && <RequestDetail go={go} notify={notify} />}
          {screen === "request-success" && <RequestSuccess go={go} />}
          {screen === "workers" && <WorkersScreen go={go} setWorker={setSelectedWorker} />}
          {screen === "worker-detail" && <WorkerDetail worker={selectedWorker} go={go} />}
          {screen === "worker-request" && <WorkerRequest worker={selectedWorker} go={go} notify={notify} />}
          {screen === "marketplace" && <MarketplaceScreen go={go} setProduct={setSelectedProduct} />}
          {screen === "product" && <ProductScreen product={selectedProduct} go={go} setCartCount={setCartCount} cartCount={cartCount} />}
          {screen === "cart" && <CartScreen go={go} cartCount={cartCount} setCartCount={setCartCount} />}
          {screen === "checkout" && <CheckoutScreen go={go} notify={notify} />}
          {screen === "orders" && <OrdersScreen go={go} />}
          {screen === "subscription" && <SubscriptionScreen notify={notify} />}
          {screen === "sos" && <SOSScreen state={sosState} setState={setSosState} go={go} />}
        </main>
        {isRoot && <BottomNav active={screen} onChange={navTo} />}
        <button onClick={() => { setSosState("confirm"); go("sos"); }} aria-label="Emergency SOS" className="fixed bottom-[76px] right-5 z-20 flex h-12 items-center gap-2 rounded-full bg-[#ba3d3c] px-4 text-xs font-bold tracking-wide text-white shadow-[0_8px_24px_rgba(186,61,60,.28)] active:scale-95">
          <Shield size={16} /> SOS
        </button>
        {toast && <div className="fixed left-1/2 top-4 z-50 flex -translate-x-1/2 items-center gap-2 rounded-2xl bg-[#17333a] px-4 py-3 text-xs font-semibold text-white shadow-xl"><CircleCheck size={16} className="text-[#8ed7b1]" />{toast}</div>}
      </div>
    </div>
  );
}

function TopBar({ screen, onBack, onProfile, onNotifications, isRoot }: { screen: Screen; onBack?: () => void; onProfile: () => void; onNotifications: () => void; isRoot: boolean }) {
  const titles: Record<string, string> = { visitors: "Visitors", community: "Community", payments: "Payments", services: "Services", profile: "My profile", notifications: "Notifications", invite: "Invite visitor", pass: "Visitor pass", parking: "Visitor parking", kids: "Family watch", amenities: "Book an amenity", "amenity-detail": "Amenity details", "booking-success": "Booking confirmed", invoice: "Review invoice", "payment-method": "Choose payment", "payment-processing": "Processing payment", "payment-success": "Payment complete", request: "Raise a request", "request-detail": "Request details", "request-success": "Request submitted", workers: "Community pros", "worker-detail": "Pro profile", "worker-request": "Request a pro", marketplace: "Community market", product: "Product details", cart: "Your basket", checkout: "Checkout", orders: "Orders", subscription: "Your subscription", sos: "Emergency support" };
  const title = screen === "home" ? "" : titles[screen] ?? "Resident";
  return <header className="flex items-center justify-between px-5 pb-3 pt-5">
    <div className="flex items-center gap-3">
      {onBack ? <button onClick={onBack} className="grid h-10 w-10 place-items-center rounded-full bg-white text-[#17333a] shadow-sm"><ArrowLeft size={19} /></button> : <div className="grid h-10 w-10 place-items-center rounded-2xl bg-[#17333a] text-[#d5f0df]"><Home size={19} /></div>}
      {isRoot && screen === "home" ? <div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#668086]">Good afternoon</p><p className="text-base font-bold">Aarav, welcome home</p></div> : <h1 className="text-lg font-bold">{title}</h1>}
    </div>
    {!onBack && <div className="flex items-center gap-1"><button onClick={onNotifications} className="relative grid h-10 w-10 place-items-center rounded-full bg-white text-[#42616a] shadow-sm"><Bell size={18} /><span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-[#d9774a]" /></button><button onClick={onProfile} className="grid h-10 w-10 place-items-center rounded-full bg-[#d8ebe3] text-xs font-bold text-[#1e5b50]">AP</button></div>}
  </header>;
}

function BottomNav({ active, onChange }: { active: Screen; onChange: (s: Screen) => void }) {
  return <nav className="fixed bottom-0 left-1/2 z-30 flex w-full max-w-[430px] -translate-x-1/2 justify-around border-t border-[#dce9e3] bg-[#fbfdfb]/95 px-2 pb-[max(10px,env(safe-area-inset-bottom))] pt-2 backdrop-blur">
    {nav.map(({ id, label, icon }) => <button key={id} onClick={() => onChange(id)} className={`flex min-w-[58px] flex-col items-center gap-1 rounded-xl px-2 py-1 text-[10px] font-semibold transition ${active === id ? "text-[#1a725e]" : "text-[#82979a]"}`}><span className={`grid h-7 w-8 place-items-center rounded-full ${active === id ? "bg-[#d8efe4]" : ""}`}><AppIcon icon={icon} size={18} /></span>{label}</button>)}
  </nav>;
}

function SectionTitle({ title, action, onAction }: { title: string; action?: string; onAction?: () => void }) {
  return <div className="mb-3 flex items-center justify-between"><h2 className="text-[15px] font-bold text-[#24454b]">{title}</h2>{action && <button onClick={onAction} className="flex items-center gap-1 text-xs font-bold text-[#1a725e]">{action}<ChevronRight size={14} /></button>}</div>;
}
function Card({ children, className = "", onClick }: { children: ReactNode; className?: string; onClick?: () => void }) {
  return <div onClick={onClick} className={`rounded-2xl border border-[#e1ece7] bg-white shadow-[0_4px_18px_rgba(33,76,66,.045)] ${onClick ? "cursor-pointer active:scale-[.99]" : ""} ${className}`}>{children}</div>;
}
function Pill({ children, tone = "green" }: { children: ReactNode; tone?: "green" | "amber" | "blue" | "red" | "slate" }) {
  const c = { green: "bg-[#e3f4ea] text-[#247252]", amber: "bg-[#fff1d7] text-[#a15b1f]", blue: "bg-[#e5f0fa] text-[#306a94]", red: "bg-[#fbe4e1] text-[#a13d3b]", slate: "bg-[#edf1f1] text-[#607579]" }[tone];
  return <span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${c}`}>{children}</span>;
}
function IconTile({ icon: Icon, label, onClick, tone = "green" }: { icon: IconType; label: string; onClick: () => void; tone?: string }) {
  const tones: Record<string, string> = { green: "bg-[#e2f1e8] text-[#247252]", blue: "bg-[#e5eff7] text-[#326c94]", amber: "bg-[#fff1d9] text-[#9b611f]", rose: "bg-[#f8e5e2] text-[#a24c45]" };
  return <button onClick={onClick} className="flex min-w-[68px] flex-1 flex-col items-center gap-2 text-center text-[10px] font-semibold text-[#527075]"><span className={`grid h-12 w-12 place-items-center rounded-2xl ${tones[tone] || tones.green}`}><Icon size={20} /></span>{label}</button>;
}

function HomeScreen({ go, notify }: { go: (s: Screen) => void; notify: (s: string) => void }) {
  return <div className="space-y-5">
    <div className="rounded-[22px] bg-[#17333a] p-5 text-white shadow-lg shadow-[#17333a]/10"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#a3cbbb]">Your community</p><p className="mt-1 text-xl font-bold">Willow Creek Estates</p><p className="mt-1 text-xs text-[#bad0ca]">Flat A-1204 · Tower A</p></div><div className="rounded-xl bg-white/10 px-2 py-1 text-[10px] font-semibold text-[#c9e8d3]">28°C · Clear</div></div><div className="mt-5 grid grid-cols-3 divide-x divide-white/15"><div><p className="text-2xl font-bold">3</p><p className="mt-1 text-[10px] text-[#b3cbc5]">Today&apos;s visitors</p></div><div className="pl-3"><p className="text-2xl font-bold">₹4,850</p><p className="mt-1 text-[10px] text-[#b3cbc5]">Due Jun 10</p></div><div className="pl-3"><p className="text-2xl font-bold">1</p><p className="mt-1 text-[10px] text-[#b3cbc5]">Open request</p></div></div></div>
    <div><SectionTitle title="Quick access" /><div className="flex gap-3"><IconTile icon={Users} label="Invite visitor" onClick={() => go("invite")} tone="green" /><IconTile icon={Car} label="Parking" onClick={() => go("parking")} tone="blue" /><IconTile icon={CalendarDays} label="Amenities" onClick={() => go("amenities")} tone="amber" /><IconTile icon={ShoppingBag} label="Market" onClick={() => go("marketplace")} tone="rose" /></div></div>
    <Card className="overflow-hidden" onClick={() => go("pass")}><div className="flex items-center justify-between border-b border-[#edf2ef] px-4 py-3"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#f8e6e5] text-[#a44b45]"><Users size={16} /></span><div><p className="text-xs font-bold">Ananya Mehta is visiting</p><p className="text-[10px] text-[#789094]">Arriving today · 2:30 PM</p></div></div><Pill tone="green">At gate</Pill></div><div className="flex items-center justify-between px-4 py-3 text-xs"><span className="font-semibold text-[#527075]">View visitor pass</span><ChevronRight size={16} className="text-[#73918e]" /></div></Card>
    <Card className="p-4" onClick={() => go("invoice")}><div className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#fff0d7] text-[#a6621d]"><Receipt size={19} /></span><div><p className="text-xs font-bold">Maintenance bill</p><p className="mt-1 text-[11px] text-[#7a8f91]">June 2024 · Due Jun 10</p></div></div><div className="text-right"><p className="text-sm font-bold">₹4,850</p><Pill tone="amber">Due soon</Pill></div></div></Card>
    <div><SectionTitle title="Your day" action="See all" onAction={() => go("notifications")} /><div className="space-y-2"><Card className="flex items-center gap-3 p-3" onClick={() => go("amenity-detail")}><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e3edf7] text-[#3d7294]"><CalendarDays size={17} /></span><div className="flex-1"><p className="text-xs font-bold">Sky Lounge booking</p><p className="mt-1 text-[10px] text-[#809295]">Saturday · 7:00 PM · 6 people</p></div><ChevronRight size={15} className="text-[#9aa" /></Card><Card className="flex items-center gap-3 p-3" onClick={() => go("request-detail")}><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#fff0d9] text-[#a26423]"><Wrench size={17} /></span><div className="flex-1"><p className="text-xs font-bold">Water pressure in master bath</p><p className="mt-1 text-[10px] text-[#809295]">Technician by 4:00 PM</p></div><Pill tone="amber">In progress</Pill></Card></div></div>
    <div><SectionTitle title="From around Willow Creek" action="Community" onAction={() => go("community")} /><Card className="overflow-hidden"><div className="h-24 bg-[linear-gradient(120deg,#dcecdf,#f6e8c9)] p-4"><div className="flex h-full items-end justify-between"><div><Pill tone="green">This weekend</Pill><p className="mt-2 text-sm font-bold text-[#244b46]">Monsoon market at the Clubhouse</p></div><span className="text-3xl">✦</span></div></div><div className="flex items-center justify-between px-4 py-3 text-[11px] text-[#6c8585]"><span>Saturday, 10:00 AM – 4:00 PM</span><span className="font-bold text-[#1a725e]">View notice</span></div></Card></div>
    <button onClick={() => { notify("Family watch is ready"); go("kids"); }} className="flex w-full items-center gap-3 rounded-2xl border border-[#d7ebe1] bg-[#eef8f1] p-4 text-left"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#d3eddb] text-[#317553]"><Shield size={19} /></span><div className="flex-1"><p className="text-xs font-bold text-[#245c46]">Family watch</p><p className="mt-1 text-[10px] text-[#5f8170]">Mira is in the play zone · tag battery 78%</p></div><ChevronRight size={16} className="text-[#4b8b68]" /></button>
  </div>;
}

function VisitorsScreen({ go, setSelected, notify }: { go: (s: Screen) => void; setSelected: (v: typeof visitors[0]) => void; notify: (s: string) => void }) {
  const open = (v: typeof visitors[0]) => { setSelected(v); go("pass"); };
  return <div className="space-y-5"><div className="flex gap-2"><button onClick={() => go("invite")} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-[#1a725e] py-3 text-xs font-bold text-white"><Plus size={16} />Invite visitor</button><button onClick={() => go("parking")} className="flex flex-1 items-center justify-center gap-2 rounded-xl border border-[#cfe1d9] bg-white py-3 text-xs font-bold text-[#1a725e]"><Car size={16} />Parking</button></div><Card className="flex items-center gap-3 bg-[#edf7f2] p-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#d1ebde] text-[#287258]"><QrCode size={19} /></span><div className="flex-1"><p className="text-xs font-bold">Gate is calm today</p><p className="mt-1 text-[10px] text-[#5c8174]">Your active passes are ready to show.</p></div><ChevronRight size={16} className="text-[#398069]" /></Card><div><SectionTitle title="Visitor history" action="Filter" onAction={() => notify("Showing all visitor activity")} /><div className="space-y-2">{visitors.map((v) => <Card key={v.name} className="flex items-center gap-3 p-3" onClick={() => open(v)}><div className={`grid h-10 w-10 place-items-center rounded-full text-xs font-bold ${v.color}`}>{v.initials}</div><div className="flex-1"><div className="flex items-center gap-2"><p className="text-xs font-bold">{v.name}</p><span className="text-[9px] text-[#839396]">{v.relation}</span></div><p className="mt-1 text-[10px] text-[#809295]">{v.date}</p></div><Pill tone={v.status === "Current" ? "green" : v.status === "Upcoming" ? "blue" : v.status === "Cancelled" ? "slate" : "green"}>{v.status}</Pill></Card>)}</div></div><Card className="p-4"><p className="text-xs font-bold">Need to track a child?</p><p className="mt-1 text-[11px] text-[#7b9091]">See zone-level updates for your family&apos;s connected tags.</p><button onClick={() => go("kids")} className="mt-3 text-xs font-bold text-[#1a725e]">Open family watch →</button></Card></div>;
}

function InviteScreen({ onDone }: { onDone: () => void }) {
  const [sent, setSent] = useState(false);
  return <div className="space-y-5"><Card className="space-y-4 p-4"><Field label="Visitor name" placeholder="e.g. Ananya Mehta" /><Field label="Mobile number" placeholder="+91 98765 43210" /><div className="grid grid-cols-2 gap-3"><Field label="Date" placeholder="Today, 24 May" /><Field label="Arrival time" placeholder="2:30 PM" /></div><Field label="Vehicle number (optional)" placeholder="MH 12 AB 4521" /><div><label className="mb-2 block text-xs font-bold text-[#46666b]">Visit purpose</label><div className="flex flex-wrap gap-2">{["Guest", "Delivery", "Cab", "Family"].map(x => <button key={x} className={`rounded-full border border-[#d5e4df] px-3 py-2 text-[11px] font-semibold ${x === "Guest" ? "bg-[#e2f1e8] text-[#247252]" : "bg-white text-[#698184]"}`}>{x}</button>)}</div></div></Card><div className="rounded-xl bg-[#fff6e6] p-3 text-[11px] leading-relaxed text-[#88622c]"><Info size={15} className="mr-2 inline" />Your visitor receives a secure pass. You can cancel or edit it anytime before entry.</div><button disabled={sent} onClick={() => { setSent(true); setTimeout(onDone, 500); }} className="w-full rounded-xl bg-[#1a725e] py-3.5 text-xs font-bold text-white disabled:opacity-60">{sent ? "Sending invite…" : "Send visitor invite"}</button></div>;
}
function PassScreen({ visitor, go, notify }: { visitor: typeof visitors[0]; go: (s: Screen) => void; notify: (s: string) => void }) {
  const [cancelled, setCancelled] = useState(false);
  return <div className="space-y-4"><Card className="overflow-hidden"><div className="bg-[#17333a] px-5 py-5 text-white"><div className="flex items-start justify-between"><div><p className="text-[10px] uppercase tracking-[.18em] text-[#a9cdbd]">Willow Creek Estates</p><p className="mt-1 text-xl font-bold">Visitor access pass</p></div><QrCode size={28} className="text-[#bce2cb]" /></div><div className="mt-5 flex items-center gap-3"><div className={`grid h-12 w-12 place-items-center rounded-full text-sm font-bold ${visitor.color}`}>{visitor.initials}</div><div><p className="font-bold">{visitor.name}</p><p className="text-xs text-[#b4cbc4]">{visitor.relation} · {visitor.date}</p></div></div></div><div className="flex flex-col items-center p-6"><div className={`grid h-40 w-40 place-items-center rounded-2xl border-8 ${cancelled ? "border-[#f4dedc] opacity-40" : "border-[#e2f0e8]"}`}><QrCode size={130} strokeWidth={1.1} /></div><p className={`mt-4 text-xs font-bold ${cancelled ? "text-[#aa4844]" : "text-[#25704f]"}`}>{cancelled ? "Pass cancelled" : "Show this at the security gate"}</p><p className="mt-1 text-center text-[10px] text-[#809295]">{cancelled ? "This pass can no longer be used." : "Pass expires today at 11:59 PM · ID WCE-7F2A"}</p></div></Card><div className="grid grid-cols-3 gap-2"><button onClick={() => notify("Pass link copied")} className="flex flex-col items-center gap-2 rounded-xl border border-[#d8e6e0] bg-white py-3 text-[10px] font-bold text-[#476970]"><Share2 size={17} />Share</button><button onClick={() => notify("Edit visitor details")} className="flex flex-col items-center gap-2 rounded-xl border border-[#d8e6e0] bg-white py-3 text-[10px] font-bold text-[#476970]"><FileText size={17} />Edit</button><button onClick={() => setCancelled(true)} className="flex flex-col items-center gap-2 rounded-xl border border-[#f0d9d6] bg-white py-3 text-[10px] font-bold text-[#aa4844]"><X size={17} />Cancel</button></div><button onClick={() => go("parking")} className="flex w-full items-center justify-between rounded-xl bg-[#e7f2f7] p-4 text-left"><span><p className="text-xs font-bold text-[#275f7c]">Reserve visitor parking</p><p className="mt-1 text-[10px] text-[#5f7f8b]">Slot B-14 is recommended for this visit.</p></span><ChevronRight size={17} className="text-[#3c7894]" /></button></div>;
}
function ParkingScreen({ notify }: { notify: (s: string) => void }) {
  const [confirmed, setConfirmed] = useState(false);
  return <div className="space-y-5"><Card className="overflow-hidden"><div className="flex items-center justify-between bg-[#e6f0f4] px-4 py-4"><div><p className="text-xs font-bold text-[#2c6077]">Visitor parking · Today</p><p className="mt-1 text-[10px] text-[#66828c]">For Ananya Mehta · 2:30 PM</p></div><Pill tone="blue">18 spots open</Pill></div><div className="grid grid-cols-4 gap-2 bg-[#f8fbfb] p-4">{["A-02","A-03","B-14","B-15","C-08","C-09","D-21","D-22","E-04","E-05","F-10","F-11"].map((x,i) => <button key={x} onClick={() => notify(`${x} is ${i === 2 ? "recommended" : "available"}`)} className={`h-12 rounded-lg border text-[10px] font-bold ${i === 2 ? "border-[#3b8095] bg-[#bfe1e5] text-[#245f6b]" : "border-[#dce9e6] bg-white text-[#6c8589]"}`}>{x}</button>)}</div><div className="flex items-center justify-center gap-4 border-t border-[#e9f0ee] py-3 text-[10px] text-[#70878a]"><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-[#bfe1e5]" />Recommended</span><span><i className="mr-1 inline-block h-2 w-2 rounded-full bg-white ring-1 ring-[#dce9e6]" />Available</span></div></Card><Card className="p-4"><div className="flex items-center justify-between"><div><p className="text-xs font-bold">Recommended slot</p><p className="mt-1 text-[11px] text-[#809295]">Closest to Tower A lift lobby</p></div><p className="text-lg font-bold text-[#1a725e]">B-14</p></div><div className="mt-4 flex items-center gap-2 text-[10px] text-[#6d8589]"><MapPin size={14} />2 min walk · Covered · CCTV monitored</div></Card><button onClick={() => { setConfirmed(true); notify("Parking B-14 reserved"); }} disabled={confirmed} className="w-full rounded-xl bg-[#1a725e] py-3.5 text-xs font-bold text-white disabled:bg-[#80ae9c]">{confirmed ? "Parking confirmed · B-14" : "Confirm visitor parking"}</button></div>;
}
function KidsScreen({ notify }: { notify: (s: string) => void }) {
  return <div className="space-y-5"><Card className="p-4"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-full bg-[#f4dfd0] text-sm font-bold text-[#93533d]">MK</div><div className="flex-1"><p className="text-sm font-bold">Mira Kapoor <span className="ml-1 text-[10px] font-normal text-[#839496]">8 yrs</span></p><p className="mt-1 text-[11px] text-[#3b8067]">At Play Zone · Tower B podium</p></div><span className="h-2.5 w-2.5 rounded-full bg-[#48a673]" /></div><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-xl bg-[#f4f8f5] p-3"><p className="text-[10px] text-[#7d9292]">Last seen</p><p className="mt-1 text-xs font-bold">12:18 PM</p><p className="mt-1 text-[10px] text-[#4e7f6c]">Play Zone · Tower B</p></div><div className="rounded-xl bg-[#f4f8f5] p-3"><p className="text-[10px] text-[#7d9292]">Tag battery</p><p className="mt-1 text-xs font-bold">78%</p><p className="mt-1 text-[10px] text-[#4e7f6c]">Good for 6 days</p></div></div></Card><Card className="p-4"><SectionTitle title="Recent movement" /><div className="space-y-4 border-l border-[#d5e5dd] pl-4">{[["12:18 PM","Play Zone","Current location"],["12:02 PM","Pool deck","Entered zone"],["11:41 AM","Tower B lobby","Exited zone"]].map(([time,place,desc],i) => <div key={time} className="relative"><span className={`absolute -left-[21px] top-0.5 h-2.5 w-2.5 rounded-full border-2 border-white ${i === 0 ? "bg-[#3c9c70]" : "bg-[#bfd8cc]"}`} /><p className="text-[10px] font-bold text-[#6b8588]">{time}</p><p className="mt-1 text-xs font-bold">{place}</p><p className="mt-0.5 text-[10px] text-[#849697]">{desc}</p></div>)}</div></Card><Card className="p-4"><SectionTitle title="Authorized pickup" action="Manage" onAction={() => notify("Pickup permissions opened")} /><div className="flex gap-4"><div className="text-center"><div className="mx-auto grid h-10 w-10 place-items-center rounded-full bg-[#e5eef4] text-xs font-bold text-[#44728c]">RK</div><p className="mt-1 text-[10px] font-semibold">Rohan Kapoor</p></div><div className="text-center"><div className="mx-auto grid h-10 w-10 place-items-center rounded-full bg-[#f4e3dc] text-xs font-bold text-[#985843]">NP</div><p className="mt-1 text-[10px] font-semibold">Nisha (nanny)</p></div><button onClick={() => notify("Add a pickup person")} className="grid h-10 w-10 place-items-center rounded-full border border-dashed border-[#bdd4c9] text-[#398067]"><Plus size={17} /></button></div></Card><button onClick={() => notify("Live location shared with security desk")} className="w-full rounded-xl border border-[#cfe2d9] bg-white py-3 text-xs font-bold text-[#1a725e]">Share update with security</button></div>;
}

function CommunityScreen({ go, setAmenity, setProduct, notify }: { go: (s: Screen) => void; setAmenity: (a: typeof amenities[0]) => void; setProduct: (p: typeof products[0]) => void; notify: (s: string) => void }) {
  return <div className="space-y-5"><div className="flex items-center gap-2 rounded-xl border border-[#dbe8e1] bg-white px-3 py-2"><Search size={17} className="text-[#8aa09e]" /><input className="w-full bg-transparent text-xs outline-none" placeholder="Search community, amenities or market" /></div><div><SectionTitle title="Made for life here" /><div className="grid grid-cols-2 gap-3"><Card className="p-4" onClick={() => go("amenities")}><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#e6f0df] text-[#497a52]"><CalendarDays size={18} /></div><p className="mt-3 text-xs font-bold">Book amenities</p><p className="mt-1 text-[10px] text-[#819394]">Pool, lounge, courts</p></Card><Card className="p-4" onClick={() => go("marketplace")}><div className="grid h-9 w-9 place-items-center rounded-xl bg-[#f6e4d4] text-[#a2603f]"><ShoppingBag size={18} /></div><p className="mt-3 text-xs font-bold">Community market</p><p className="mt-1 text-[10px] text-[#819394]">Local vendors & care</p></Card></div></div><div><SectionTitle title="This week in Willow Creek" /><Card className="overflow-hidden" onClick={() => notify("Event details opened")}><div className="flex items-end justify-between bg-[linear-gradient(120deg,#d8e9dc,#f5dfc3)] p-4"><div><Pill tone="amber">Saturday · 10 AM</Pill><p className="mt-3 text-base font-bold text-[#295246]">Monsoon market</p><p className="mt-1 text-[10px] text-[#52766b]">Clubhouse lawn · 24 local makers</p></div><span className="text-4xl text-[#8ab394]">✦</span></div><div className="px-4 py-3 text-[10px] text-[#718a8a]">Bring your reusable bags · Open to all residents</div></Card></div><div><SectionTitle title="Popular this week" action="Browse all" onAction={() => go("marketplace")} /><div className="space-y-2">{amenities.slice(0,2).map(a => <Card key={a.name} className="flex items-center gap-3 p-3" onClick={() => { setAmenity(a); go("amenity-detail"); }}><div className={`grid h-11 w-11 place-items-center rounded-xl ${a.color} text-[#347263]`}><a.icon size={19} /></div><div className="flex-1"><p className="text-xs font-bold">{a.name}</p><p className="mt-1 text-[10px] text-[#839395]">{a.meta}</p></div><ChevronRight size={16} className="text-[#91a3a1]" /></Card>)}</div></div><button onClick={() => { setProduct(products[0]); go("product"); }} className="flex w-full items-center justify-between rounded-2xl bg-[#17333a] p-4 text-left text-white"><div><p className="text-[10px] uppercase tracking-[.16em] text-[#a9cdbd]">From a neighbour&apos;s kitchen</p><p className="mt-1 text-sm font-bold">Fresh Alphonso mangoes</p><p className="mt-1 text-[10px] text-[#b5ccc6]">Delivered tomorrow · ₹860</p></div><ArrowRight size={18} className="text-[#c1e4cc]" /></button></div>;
}

function PaymentsScreen({ go, notify }: { go: (s: Screen) => void; notify: (s: string) => void }) {
  return <div className="space-y-5"><Card className="bg-[#17333a] p-5 text-white"><p className="text-[10px] uppercase tracking-[.16em] text-[#a8cabd]">Outstanding balance</p><p className="mt-2 text-3xl font-bold">₹4,850</p><p className="mt-1 text-xs text-[#b6cdc7]">Due June 10 · Maintenance & utilities</p><button onClick={() => go("invoice")} className="mt-4 flex items-center gap-2 rounded-lg bg-[#d7f0df] px-3 py-2 text-xs font-bold text-[#1b664f]">Review & pay <ArrowRight size={14} /></button></Card><div className="grid grid-cols-2 gap-3"><Card className="p-4" onClick={() => go("invoice")}><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#fff0d5] text-[#a36522]"><Receipt size={17} /></span><p className="mt-3 text-xs font-bold">Maintenance</p><p className="mt-1 text-[11px] text-[#809294]">₹4,250 · Due soon</p></Card><Card className="p-4" onClick={() => go("invoice")}><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e2eff5] text-[#3d758d]"><Droplets size={17} /></span><p className="mt-3 text-xs font-bold">Utilities</p><p className="mt-1 text-[11px] text-[#809294]">₹600 · May usage</p></Card></div><div><SectionTitle title="Recent payments" action="View history" onAction={() => go("orders")} /><div className="space-y-2">{[["Maintenance · May","May 10, 2024","₹4,250","Paid","green"],["Clubhouse booking","May 04, 2024","₹1,200","Paid","green"],["Parking deposit","Apr 28, 2024","₹500","Refunded","blue"]].map(x => <Card key={x[0]} className="flex items-center gap-3 p-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#eff5f2] text-[#508174]"><CreditCard size={16} /></span><div className="flex-1"><p className="text-xs font-bold">{x[0]}</p><p className="mt-1 text-[10px] text-[#8a9a9b]">{x[1]}</p></div><div className="text-right"><p className="text-xs font-bold">{x[2]}</p><Pill tone={x[4] as "green" | "blue"}>{x[3]}</Pill></div></Card>)}</div></div><button onClick={() => notify("Payment statement downloaded")} className="flex w-full items-center justify-center gap-2 rounded-xl border border-[#d2e4dc] bg-white py-3 text-xs font-bold text-[#46716a]"><Download size={15} />Download statement</button></div>;
}

function InvoiceScreen({ go }: { go: (s: Screen) => void }) { return <div className="space-y-5"><Card className="p-5"><div className="flex items-start justify-between border-b border-[#e4eeea] pb-4"><div><p className="text-xs text-[#7d9293]">WILLOW CREEK ESTATES</p><p className="mt-1 text-sm font-bold">Maintenance invoice</p><p className="mt-1 text-[10px] text-[#829394]">INV-WCE-2406 · June 2024</p></div><Receipt size={23} className="text-[#398067]" /></div><div className="space-y-3 py-4 text-xs"><div className="flex justify-between"><span className="text-[#718789]">Monthly maintenance</span><b>₹3,800</b></div><div className="flex justify-between"><span className="text-[#718789]">Clubhouse & amenities</span><b>₹350</b></div><div className="flex justify-between"><span className="text-[#718789]">Reserve fund contribution</span><b>₹100</b></div><div className="flex justify-between border-t border-[#e4eeea] pt-3 text-sm"><span className="font-bold">Total due</span><b>₹4,250</b></div></div><div className="rounded-xl bg-[#fff4df] p-3 text-[10px] text-[#8b642b]">Payment due by June 10, 2024. Late fee of ₹150 applies after the due date.</div></Card><Card className="p-4"><div className="flex items-center justify-between"><div><p className="text-xs font-bold">Payment method</p><p className="mt-1 text-[11px] text-[#809294]">HDFC Bank · •••• 3821</p></div><button className="text-xs font-bold text-[#1a725e]">Change</button></div></Card><button onClick={() => go("payment-method")} className="w-full rounded-xl bg-[#1a725e] py-3.5 text-xs font-bold text-white">Pay ₹4,250</button></div> }
function PaymentMethodScreen({ go, setPaymentState }: { go: (s: Screen) => void; setPaymentState: (s: "idle" | "processing" | "success") => void }) { return <div className="space-y-4"><Card className="p-4"><p className="text-xs font-bold">Choose how to pay</p><div className="mt-3 space-y-2">{[["HDFC Bank","•••• 3821","Recommended"],["UPI","aarav.k@okhdfcbank","Fastest"],["Visa credit card","•••• 1842",""]].map((m,i) => <button key={m[0]} onClick={() => { if (i !== 0) setPaymentState("idle"); }} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left ${i === 0 ? "border-[#66ae91] bg-[#edf8f0]" : "border-[#e2ebe7] bg-white"}`}><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#e7f0ee] text-[#397461]"><CreditCard size={16} /></span><span className="flex-1"><p className="text-xs font-bold">{m[0]}</p><p className="mt-1 text-[10px] text-[#819294]">{m[1]}</p></span><span className="text-[9px] font-semibold text-[#328066]">{m[2]}</span>{i === 0 && <CircleCheck size={16} className="text-[#2e8563]" />}</button>)}</div></Card><div className="flex items-center justify-between px-1 text-xs"><span className="text-[#7d9294]">You pay</span><b className="text-lg">₹4,250</b></div><button onClick={() => { setPaymentState("processing"); go("payment-processing"); }} className="w-full rounded-xl bg-[#1a725e] py-3.5 text-xs font-bold text-white">Continue securely</button><p className="text-center text-[10px] text-[#8a9b9b]"><Shield size={12} className="mr-1 inline text-[#398067]" />Payments are encrypted and secure</p></div> }
function PaymentProcessing({ go, setPaymentState }: { go: (s: Screen) => void; setPaymentState: (s: "idle" | "processing" | "success") => void }) { return <div className="flex min-h-[450px] flex-col items-center justify-center text-center"><div className="grid h-20 w-20 place-items-center rounded-full bg-[#e0f1e8] text-[#398067]"><CreditCard size={32} className="animate-pulse" /></div><h2 className="mt-5 text-xl font-bold">Securely processing</h2><p className="mt-2 max-w-[250px] text-xs leading-relaxed text-[#7f9394]">We&apos;re confirming your payment with HDFC Bank. Please keep this screen open.</p><div className="mt-6 h-1.5 w-48 overflow-hidden rounded-full bg-[#dbe9e2]"><div className="h-full w-2/3 rounded-full bg-[#398067]" /></div><button onClick={() => { setPaymentState("success"); go("payment-success"); }} className="mt-10 text-xs font-bold text-[#1a725e]">See success receipt</button></div> }
function PaymentSuccess({ go }: { go: (s: Screen) => void }) { return <div className="space-y-5 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-[#dff2e5] text-[#2c855d]"><Check size={38} /></div><div><h2 className="text-2xl font-bold">Payment received</h2><p className="mt-2 text-xs text-[#7e9392]">Your June maintenance is all settled.</p></div><Card className="p-5 text-left"><div className="flex justify-between text-xs"><span className="text-[#829394]">Amount paid</span><b className="text-lg">₹4,250</b></div><div className="mt-4 flex justify-between text-[11px]"><span className="text-[#829394]">Receipt</span><b>WCE-REC-6104</b></div><div className="mt-2 flex justify-between text-[11px]"><span className="text-[#829394]">Paid on</span><b>24 May 2024 · 12:46 PM</b></div></Card><button onClick={() => go("payments")} className="w-full rounded-xl bg-[#1a725e] py-3.5 text-xs font-bold text-white">Back to payments</button><button className="flex w-full items-center justify-center gap-2 py-2 text-xs font-bold text-[#46756a]"><Download size={15} />Download receipt</button></div> }

function AmenitiesScreen({ go, setAmenity }: { go: (s: Screen) => void; setAmenity: (a: typeof amenities[0]) => void }) { return <div className="space-y-5"><div className="flex gap-2 overflow-auto pb-1">{["All", "Popular", "Sports", "Social"].map((x,i)=><button key={x} className={`whitespace-nowrap rounded-full px-4 py-2 text-[11px] font-bold ${i===0?"bg-[#17333a] text-white":"border border-[#d7e5df] bg-white text-[#678184]"}`}>{x}</button>)}</div><div className="space-y-3">{amenities.map(a=><Card key={a.name} onClick={()=>{setAmenity(a);go("amenity-detail")}} className="overflow-hidden"><div className={`flex h-28 items-end ${a.color} p-4`}><div><Pill tone="green">{a.price}</Pill><p className="mt-2 text-sm font-bold">{a.name}</p></div><a.icon size={33} className="ml-auto text-[#4d8a78]" /></div><div className="flex items-center justify-between p-4"><div><p className="text-[10px] text-[#779091]">{a.meta}</p><p className="mt-1 text-xs text-[#557174]">{a.desc}</p></div><ChevronRight size={16} className="text-[#8ba09e]" /></div></Card>)}</div></div> }
function AmenityDetail({ amenity, go }: { amenity: typeof amenities[0]; go: (s: Screen) => void }) { const [booked,setBooked]=useState(false); return <div className="space-y-4"><Card className={`p-5 ${amenity.color}`}><amenity.icon size={28} className="text-[#398067]" /><h2 className="mt-4 text-xl font-bold">{amenity.name}</h2><p className="mt-1 text-xs text-[#5f7775]">{amenity.meta}</p></Card><Card className="space-y-4 p-4"><div><p className="text-xs font-bold">Choose date</p><div className="mt-2 flex gap-2">{["Sat 25","Sun 26","Mon 27"].map((x,i)=><button key={x} className={`flex-1 rounded-xl border py-2 text-[10px] font-bold ${i===0?"border-[#65a88c] bg-[#e3f2e8] text-[#247252]":"border-[#e1ebe6] text-[#71888a]"}`}>{x}</button>)}</div></div><div><p className="text-xs font-bold">Available time slots</p><div className="mt-2 grid grid-cols-3 gap-2">{["5:00 PM","7:00 PM","9:00 PM"].map((x,i)=><button key={x} className={`rounded-xl border py-2 text-[10px] font-bold ${i===1?"border-[#65a88c] bg-[#e3f2e8] text-[#247252]":"border-[#e1ebe6] text-[#71888a]"}`}>{x}</button>)}</div></div><div className="flex items-center justify-between border-t border-[#e6efea] pt-3 text-xs"><span className="text-[#789092]">For 6 people · 2 hours</span><b>{amenity.price}</b></div></Card><Card className="p-4"><p className="text-xs font-bold">Good to know</p><p className="mt-2 text-[11px] leading-relaxed text-[#718789]">Please arrive 10 minutes early. Residents can cancel up to 4 hours before the slot. Capacity and access rules are shown on your pass.</p></Card><button onClick={()=>{setBooked(true);go("booking-success")}} disabled={booked} className="w-full rounded-xl bg-[#1a725e] py-3.5 text-xs font-bold text-white disabled:opacity-60">{booked?"Booking…":"Review & book · ₹1,200"}</button></div> }
function BookingSuccess({ go }: { go: (s: Screen) => void }) { return <div className="space-y-5 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-[#dff2e5] text-[#2c855d]"><CalendarDays size={34} /></div><div><h2 className="text-2xl font-bold">You&apos;re booked</h2><p className="mt-2 text-xs text-[#7e9392]">Sky Lounge is ready for your Saturday evening.</p></div><Card className="p-5 text-left"><div className="flex items-center justify-between"><div><p className="text-sm font-bold">Sky Lounge</p><p className="mt-1 text-[11px] text-[#809294]">Saturday, May 25 · 7:00 PM</p></div><Pill tone="green">Confirmed</Pill></div><div className="my-5 grid place-items-center rounded-xl bg-[#f6faf7] py-4"><QrCode size={92} strokeWidth={1.2} /></div><div className="flex justify-between text-[11px]"><span className="text-[#809294]">Booking ID</span><b>WCE-SL-5428</b></div><div className="mt-2 flex justify-between text-[11px]"><span className="text-[#809294]">Access</span><b>Show QR at Clubhouse</b></div></Card><button onClick={()=>go("community")} className="w-full rounded-xl bg-[#1a725e] py-3.5 text-xs font-bold text-white">Done</button></div> }

function ServicesScreen({ go, setWorker }: { go: (s: Screen) => void; setWorker: (w: typeof workers[0]) => void; notify: (s: string) => void }) { return <div className="space-y-5"><div className="grid grid-cols-2 gap-3"><Card className="p-4" onClick={()=>go("request")}><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#fff0d8] text-[#a36422]"><Plus size={18}/></span><p className="mt-3 text-xs font-bold">Raise a request</p><p className="mt-1 text-[10px] text-[#809294]">Tell us what needs care</p></Card><Card className="p-4" onClick={()=>go("workers")}><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#e2edf5] text-[#356b8c]"><Users size={18}/></span><p className="mt-3 text-xs font-bold">Hire a pro</p><p className="mt-1 text-[10px] text-[#809294]">Approved community workers</p></Card></div><div><SectionTitle title="Your requests" action="Filter" /><div className="space-y-2">{requests.map(r=><Card key={r.id} className="p-4" onClick={()=>go("request-detail")}><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold text-[#789092]">{r.id} · {r.category}</p><p className="mt-1 text-xs font-bold">{r.title}</p></div><Pill tone={r.tone as "green"|"amber"|"blue"}>{r.status}</Pill></div><div className="mt-3 flex items-center justify-between text-[10px] text-[#819394]"><span>{r.sla}</span><span>{r.updated}</span></div></Card>)}</div></div><Card className="flex items-center gap-3 border-[#d9e9e0] bg-[#eef8f1] p-4"><Shield size={20} className="text-[#388161]"/><div><p className="text-xs font-bold text-[#2d624c]">Only trusted hands</p><p className="mt-1 text-[10px] text-[#648574]">Every service pro is verified and approved by Willow Creek.</p></div></Card></div> }
function RequestForm({ onDone }: { onDone: () => void }) { const [sent,setSent]=useState(false); return <div className="space-y-4"><Card className="space-y-4 p-4"><div><label className="mb-2 block text-xs font-bold text-[#46666b]">What can we help with?</label><select className="w-full rounded-xl border border-[#d9e6e0] bg-white px-3 py-3 text-xs text-[#526f72] outline-none"><option>Plumbing</option><option>Electrical</option><option>Housekeeping</option><option>Security</option><option>Other</option></select></div><Field label="Short description" placeholder="e.g. Water pressure is low in the master bath" /><div><label className="mb-2 block text-xs font-bold text-[#46666b]">Priority</label><div className="flex gap-2">{["Routine","Soon","Urgent"].map((x,i)=><button key={x} className={`flex-1 rounded-xl border py-2 text-[10px] font-bold ${i===1?"border-[#efc779] bg-[#fff3dc] text-[#a46320]":"border-[#dce8e3] text-[#789092]"}`}>{x}</button>)}</div></div><Field label="Where should we come?" placeholder="Master bathroom · Flat A-1204" /><div><label className="mb-2 block text-xs font-bold text-[#46666b]">Add a photo (optional)</label><button className="flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-[#bed7c9] py-4 text-xs font-bold text-[#48806d]"><Camera size={16}/>Take or upload photo</button></div></Card><button disabled={sent} onClick={()=>{setSent(true);setTimeout(onDone,500)}} className="w-full rounded-xl bg-[#1a725e] py-3.5 text-xs font-bold text-white disabled:opacity-60">{sent?"Submitting…":"Submit request"}</button></div> }
function RequestDetail({ go, notify }: { go: (s: Screen) => void; notify: (s: string) => void }) {
  const timeline = [["12:10 PM", "Technician assigned", "A community technician has been assigned."], ["11:46 AM", "Request received", "Our team is reviewing the details."], ["11:42 AM", "Request raised", "You reported this from Flat A-1204."]];
  return <div className="space-y-4">
    <Card className="p-4"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold text-[#789092]">SR-2841 · PLUMBING</p><h2 className="mt-2 text-base font-bold">Water pressure in master bath</h2><p className="mt-2 text-[11px] leading-relaxed text-[#789092]">Water pressure has been low since yesterday evening. Kitchen and other bathrooms are normal.</p></div><Pill tone="amber">In progress</Pill></div><div className="mt-4 grid grid-cols-2 gap-2 rounded-xl bg-[#f5f9f6] p-3 text-[10px]"><div><p className="text-[#849697]">Response SLA</p><b className="mt-1 block">Today by 4:00 PM</b></div><div><p className="text-[#849697]">Assigned to</p><b className="mt-1 block">Ramesh Electric Works</b></div></div></Card>
    <Card className="p-4"><SectionTitle title="Progress" /><div className="space-y-5 border-l border-[#d5e6dc] pl-4">{timeline.map((x, i) => <div key={x[0]} className="relative"><span className={`absolute -left-[21px] top-0 h-2.5 w-2.5 rounded-full border-2 border-white ${i === 0 ? "bg-[#3c9c70]" : "bg-[#b9d7c7]"}`} /><p className="text-[10px] text-[#839496]">{x[0]}</p><p className="mt-1 text-xs font-bold">{x[1]}</p><p className="mt-1 text-[10px] text-[#819294]">{x[2]}</p></div>)}</div></Card>
    <Card className="p-4"><p className="text-xs font-bold">Need to add context?</p><button onClick={() => notify("Comment box opened")} className="mt-3 flex w-full items-center gap-2 rounded-xl border border-[#dbe7e2] px-3 py-3 text-left text-xs text-[#8a9a9b]"><MessageCircle size={16} />Add a comment or attachment</button></Card>
    <div className="grid grid-cols-2 gap-2"><button onClick={() => notify("Request marked resolved")} className="rounded-xl border border-[#cfe1d9] bg-white py-3 text-xs font-bold text-[#28735c]">Mark resolved</button><button onClick={() => go("request-success")} className="rounded-xl bg-[#1a725e] py-3 text-xs font-bold text-white">View resolution</button></div>
  </div>;
}
function RequestSuccess({ go }: { go: (s: Screen) => void }) { return <div className="space-y-5 text-center"><div className="mx-auto grid h-20 w-20 place-items-center rounded-full bg-[#dff2e5] text-[#2c855d]"><Check size={38}/></div><h2 className="text-2xl font-bold">All sorted</h2><p className="text-xs text-[#809294]">Your service request was resolved. How did we do?</p><Card className="p-4 text-left"><p className="text-xs font-bold">Rate the service</p><div className="mt-3 flex justify-between">{[1,2,3,4,5].map(x=><button key={x} className="grid h-10 w-10 place-items-center rounded-full bg-[#fff2d8] text-[#bd7826]"><Star size={17} fill="currentColor"/></button>)}</div><textarea className="mt-4 h-20 w-full resize-none rounded-xl border border-[#dce8e3] p-3 text-xs outline-none" placeholder="Anything you would like us to know?" /></Card><button onClick={()=>go("services")} className="w-full rounded-xl bg-[#1a725e] py-3.5 text-xs font-bold text-white">Submit rating</button></div> }

function WorkersScreen({ go, setWorker }: { go: (s: Screen) => void; setWorker: (w: typeof workers[0]) => void }) {
  return <div className="space-y-4">
    <div className="flex items-center gap-2 rounded-xl border border-[#dbe8e1] bg-white px-3 py-2"><Search size={17} className="text-[#8aa09e]" /><input className="w-full bg-transparent text-xs outline-none" placeholder="Search a service" /><SlidersHorizontal size={16} className="text-[#557b76]" /></div>
    <div className="flex gap-2 overflow-auto">{["All services", "Home care", "Repairs", "Wellness"].map((x, i) => <button key={x} className={`whitespace-nowrap rounded-full px-3 py-2 text-[10px] font-bold ${i === 0 ? "bg-[#17333a] text-white" : "border border-[#d8e6df] bg-white text-[#71898b]"}`}>{x}</button>)}</div>
    <div className="rounded-xl bg-[#edf7f0] p-3 text-[11px] text-[#527766]"><Shield size={14} className="mr-1 inline" />Verified by Willow Creek · background checked · gate access approved</div>
    <div className="space-y-2">{workers.map((w) => <Card key={w.name} className="p-4" onClick={() => { setWorker(w); go("worker-detail"); }}><div className="flex gap-3"><div className="grid h-12 w-12 place-items-center rounded-full bg-[#dcece5] text-sm font-bold text-[#39735f]">{w.initials}</div><div className="flex-1"><div className="flex items-center gap-2"><p className="text-xs font-bold">{w.name}</p><Shield size={13} className="text-[#398067]" /></div><p className="mt-1 text-[11px] text-[#789092]">{w.service}</p><div className="mt-2 flex gap-3 text-[10px]"><span className="flex items-center gap-1 text-[#9e692a]"><Star size={12} fill="currentColor" />{w.rating}</span><span className="text-[#829394]">{w.jobs}</span><Pill tone="green">{w.time}</Pill></div></div><ChevronRight size={16} className="mt-2 text-[#91a3a1]" /></div></Card>)}</div>
  </div>;
}
function WorkerDetail({ worker, go }: { worker: typeof workers[0]; go: (s: Screen) => void }) { return <div className="space-y-4"><Card className="p-5 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-[#dcece5] text-lg font-bold text-[#39735f]">{worker.initials}</div><h2 className="mt-3 text-lg font-bold">{worker.name}</h2><p className="mt-1 text-xs text-[#789092]">{worker.service} · <span className="text-[#398067]">Verified pro</span></p><div className="mt-4 flex justify-center gap-8 text-xs"><span><b>{worker.rating}</b><small className="ml-1 text-[#829394]">rating</small></span><span><b>{worker.jobs.split(" ")[0]}</b><small className="ml-1 text-[#829394]">completed</small></span><span><b>6 yrs</b><small className="ml-1 text-[#829394]">experience</small></span></div></Card><Card className="p-4"><SectionTitle title="About this pro"/><p className="text-[11px] leading-relaxed text-[#718789]">Trusted by Willow Creek residents for careful, transparent work. Rates and arrival window are shared before anything begins.</p><div className="mt-4 flex flex-wrap gap-2">{["Gate approved","Background checked","Digital payments","Service guarantee"].map(x=><Pill key={x} tone="green">{x}</Pill>)}</div></Card><Card className="p-4"><SectionTitle title="Recent resident reviews"/><p className="text-xs font-bold">“Arrived on time and explained everything.”</p><p className="mt-1 text-[10px] text-[#829394]">— Priya S. · Tower C</p></Card><button onClick={()=>go("worker-request")} className="w-full rounded-xl bg-[#1a725e] py-3.5 text-xs font-bold text-white">Request this pro</button></div> }
function WorkerRequest({ worker, go, notify }: { worker: typeof workers[0]; go: (s: Screen) => void; notify: (s: string) => void }) { const [done,setDone]=useState(false); return <div className="space-y-4"><Card className="flex items-center gap-3 p-4"><div className="grid h-11 w-11 place-items-center rounded-full bg-[#dcece5] text-sm font-bold text-[#39735f]">{worker.initials}</div><div><p className="text-xs font-bold">{worker.name}</p><p className="mt-1 text-[10px] text-[#789092]">{worker.service} · ₹450 visit fee</p></div></Card><Card className="space-y-4 p-4"><Field label="What do you need help with?" placeholder="Please describe the work" /><div className="grid grid-cols-2 gap-3"><Field label="Preferred date" placeholder="Tomorrow, May 25"/><Field label="Time window" placeholder="10 AM – 12 PM"/></div><Field label="Access notes" placeholder="Security can call on arrival" /></Card><div className="flex items-start gap-2 rounded-xl bg-[#edf7f0] p-3 text-[10px] leading-relaxed text-[#5a7e6c]"><Shield size={15} className="mt-0.5 shrink-0"/>This pro can enter only after you approve gate access. You&apos;ll pay after the visit is complete.</div><button disabled={done} onClick={()=>{setDone(true);notify("Request sent to Ramesh Electric Works");setTimeout(()=>go("services"),500)}} className="w-full rounded-xl bg-[#1a725e] py-3.5 text-xs font-bold text-white disabled:opacity-60">{done?"Sending request…":"Send request"}</button></div> }

function MarketplaceScreen({ go, setProduct }: { go: (s: Screen) => void; setProduct: (p: typeof products[0]) => void }) { return <div className="space-y-5"><div className="flex items-center gap-2 rounded-xl border border-[#dbe8e1] bg-white px-3 py-2"><Search size={17} className="text-[#8aa09e]"/><input className="w-full bg-transparent text-xs outline-none" placeholder="Search products or vendors"/><button onClick={()=>go("cart")}><ShoppingBag size={17} className="text-[#397966]"/></button></div><div className="flex gap-2 overflow-auto">{["Featured","Fresh picks","Meals","Home","Care"].map((x,i)=><button key={x} className={`whitespace-nowrap rounded-full px-3 py-2 text-[10px] font-bold ${i===0?"bg-[#17333a] text-white":"border border-[#d8e6df] bg-white text-[#71898b]"}`}>{x}</button>)}</div><Card className="overflow-hidden"><div className="bg-[#e6f0da] p-4"><Pill tone="green">Neighbour pick</Pill><p className="mt-3 text-base font-bold text-[#315b43]">Small things, closer to home.</p><p className="mt-1 text-[10px] text-[#5c7d66]">Discover trusted vendors serving Willow Creek.</p></div><div className="px-4 py-3 text-[10px] text-[#708789]">Free delivery above ₹999 · Gate-safe deliveries</div></Card><div><SectionTitle title="From your community" action="Orders" onAction={()=>go("orders")}/><div className="grid grid-cols-2 gap-3">{products.map(p=><Card key={p.name} className="overflow-hidden" onClick={()=>{setProduct(p);go("product")}}><div className={`grid h-28 place-items-center ${p.color} text-xl font-bold text-[#7b6543]`}>{p.mark}</div><div className="p-3"><p className="text-[10px] font-semibold text-[#869798]">{p.vendor}</p><p className="mt-1 min-h-[30px] text-xs font-bold leading-snug">{p.name}</p><div className="mt-3 flex items-center justify-between"><b className="text-xs">₹{p.price.toLocaleString()}</b><span className="grid h-7 w-7 place-items-center rounded-full bg-[#e1f1e6] text-[#267457]"><Plus size={15}/></span></div></div></Card>)}</div></div><Card className="flex items-center gap-3 p-4" onClick={()=>go("subscription")}><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#f6e9cb] text-[#a46a20]"><CalendarDays size={18}/></span><div className="flex-1"><p className="text-xs font-bold">Weekly essentials, on autopilot</p><p className="mt-1 text-[10px] text-[#7f9291]">Manage your subscriptions</p></div><ChevronRight size={16}/></Card></div> }
function ProductScreen({ product, go, setCartCount, cartCount }: { product: typeof products[0]; go: (s: Screen) => void; setCartCount: (n:number)=>void; cartCount:number }) { return <div className="space-y-5"><Card className={`grid h-48 place-items-center ${product.color} text-3xl font-bold text-[#7b6543]`}>{product.mark}</Card><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#829394]">{product.vendor}</p><h2 className="mt-2 text-xl font-bold">{product.name}</h2><p className="mt-2 text-xs leading-relaxed text-[#789092]">Freshly packed for residents of Willow Creek. Delivered to your doorstep with a gate-verified handoff.</p></div><Card className="p-4"><div className="flex items-center justify-between"><div><p className="text-lg font-bold">₹{product.price.toLocaleString()}</p><p className="mt-1 text-[10px] text-[#809294]">Inclusive of all taxes · Delivery tomorrow</p></div><div className="flex items-center gap-2"><button onClick={()=>setCartCount(Math.max(0,cartCount-1))} className="grid h-8 w-8 place-items-center rounded-full bg-[#edf4f0]"><Minus size={14}/></button><span className="w-4 text-center text-xs font-bold">{cartCount || 1}</span><button onClick={()=>setCartCount(cartCount+1)} className="grid h-8 w-8 place-items-center rounded-full bg-[#dff0e5] text-[#247252]"><Plus size={14}/></button></div></div></Card><button onClick={()=>{setCartCount(Math.max(1,cartCount+1));go("cart")}} className="w-full rounded-xl bg-[#1a725e] py-3.5 text-xs font-bold text-white">Add to basket · ₹{product.price.toLocaleString()}</button><button onClick={()=>go("marketplace")} className="w-full py-2 text-xs font-bold text-[#46756a]">Keep browsing</button></div> }
function CartScreen({ go, cartCount, setCartCount }: { go: (s: Screen) => void; cartCount: number; setCartCount:(n:number)=>void }) { const count=Math.max(1,cartCount); return <div className="space-y-5"><Card className="p-4"><div className="flex gap-3"><div className="grid h-16 w-16 place-items-center rounded-xl bg-[#f8e3b2] text-sm font-bold text-[#7b6543]">AM</div><div className="flex-1"><p className="text-xs font-bold">Alphonso mangoes · 2 kg</p><p className="mt-1 text-[10px] text-[#829394]">The Daily Basket</p><div className="mt-3 flex items-center gap-2"><button onClick={()=>setCartCount(Math.max(1,count-1))} className="grid h-7 w-7 place-items-center rounded-full bg-[#edf4f0]"><Minus size={13}/></button><span className="text-xs font-bold">{count}</span><button onClick={()=>setCartCount(count+1)} className="grid h-7 w-7 place-items-center rounded-full bg-[#dff0e5] text-[#247252]"><Plus size={13}/></button></div></div><b className="text-xs">₹{(860*count).toLocaleString()}</b></div></Card><Card className="space-y-3 p-4 text-xs"><div className="flex justify-between"><span className="text-[#829394]">Subtotal</span><b>₹{(860*count).toLocaleString()}</b></div><div className="flex justify-between"><span className="text-[#829394]">Delivery</span><b className="text-[#398067]">Free</b></div><div className="flex justify-between border-t border-[#e5ede9] pt-3 text-sm"><b>Total</b><b>₹{(860*count).toLocaleString()}</b></div></Card><button onClick={()=>go("checkout")} className="w-full rounded-xl bg-[#1a725e] py-3.5 text-xs font-bold text-white">Checkout</button><button onClick={()=>go("marketplace")} className="w-full py-2 text-xs font-bold text-[#46756a]">Add more from market</button></div> }
function CheckoutScreen({ go, notify }: { go: (s: Screen) => void; notify:(s:string)=>void }) { const [done,setDone]=useState(false); return <div className="space-y-4"><Card className="p-4"><p className="text-xs font-bold">Delivery to</p><div className="mt-3 flex items-center gap-3"><MapPin size={18} className="text-[#398067]"/><div><p className="text-xs font-bold">Aarav Kapoor</p><p className="mt-1 text-[10px] text-[#829394]">Flat A-1204, Tower A · Willow Creek</p></div></div></Card><Card className="p-4"><p className="text-xs font-bold">Payment</p><div className="mt-3 flex items-center gap-3 rounded-xl bg-[#f3f8f5] p-3"><CreditCard size={17} className="text-[#398067]"/><div className="flex-1"><p className="text-xs font-bold">HDFC Bank · •••• 3821</p><p className="mt-1 text-[10px] text-[#829394]">Change</p></div><CircleCheck size={16} className="text-[#398067]"/></div></Card><Card className="p-4 text-xs"><div className="flex justify-between"><span className="text-[#829394]">Arrives</span><b>Tomorrow · 7–9 AM</b></div><div className="mt-3 flex justify-between"><span className="text-[#829394]">Total</span><b>₹860</b></div></Card><button disabled={done} onClick={()=>{setDone(true);notify("Order WCE-1048 confirmed");setTimeout(()=>go("orders"),500)}} className="w-full rounded-xl bg-[#1a725e] py-3.5 text-xs font-bold text-white disabled:opacity-60">{done?"Placing order…":"Place order · ₹860"}</button></div> }
function OrdersScreen({ go }: { go:(s:Screen)=>void }) { return <div className="space-y-4"><Card className="p-4"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold text-[#789092]">ORDER WCE-1048</p><p className="mt-1 text-sm font-bold">Alphonso mangoes · 2 kg</p><p className="mt-1 text-[10px] text-[#829394]">The Daily Basket · ₹860</p></div><Pill tone="blue">Out for delivery</Pill></div><div className="mt-5 flex items-center justify-between"><div className="text-center"><span className="mx-auto grid h-7 w-7 place-items-center rounded-full bg-[#dff1e5] text-[#398067]"><Check size={14}/></span><p className="mt-1 text-[9px] font-semibold">Packed</p></div><div className="h-px flex-1 bg-[#a7cdb8]"/><div className="text-center"><span className="mx-auto grid h-7 w-7 place-items-center rounded-full bg-[#dff1e5] text-[#398067]"><PackageCheck size={14}/></span><p className="mt-1 text-[9px] font-semibold">On the way</p></div><div className="h-px flex-1 bg-[#dce8e2]"/><div className="text-center"><span className="mx-auto grid h-7 w-7 place-items-center rounded-full bg-[#edf2ef] text-[#849798]"><Home size={14}/></span><p className="mt-1 text-[9px] font-semibold">Delivered</p></div></div><button onClick={()=>go("marketplace")} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl border border-[#cfe1d9] py-2.5 text-xs font-bold text-[#397461]">Track live delivery <MapPin size={14}/></button></Card><Card className="p-4"><div className="flex items-center justify-between"><div><p className="text-xs font-bold">Nourish Kitchen · May 04</p><p className="mt-1 text-[10px] text-[#829394]">Five-day lunch plan · ₹1,450</p></div><Pill tone="green">Delivered</Pill></div><div className="mt-3 flex items-center gap-1 text-[#c07a2a]">{[1,2,3,4,5].map(x=><Star key={x} size={14} fill="currentColor"/>)}</div></Card></div> }
function SubscriptionScreen({ notify }: { notify:(s:string)=>void }) { const [paused,setPaused]=useState(false); return <div className="space-y-4"><Card className="overflow-hidden"><div className="bg-[#e7edd9] p-5"><Pill tone="green">Active subscription</Pill><h2 className="mt-3 text-xl font-bold text-[#315b43]">Weekly essentials box</h2><p className="mt-1 text-xs text-[#62806c]">The Daily Basket · every Monday</p></div><div className="space-y-3 p-4 text-xs"><div className="flex justify-between"><span className="text-[#829394]">Next delivery</span><b>May 27 · 7–9 AM</b></div><div className="flex justify-between"><span className="text-[#829394]">Amount</span><b>₹1,250 / week</b></div><div className="flex justify-between"><span className="text-[#829394]">Includes</span><b>Milk, eggs, bread, greens</b></div></div></Card><div className="grid grid-cols-2 gap-2"><button onClick={()=>{setPaused(!paused);notify(paused?"Subscription resumed":"Subscription paused until June 10")}} className="rounded-xl border border-[#cfe1d9] bg-white py-3 text-xs font-bold text-[#397461]">{paused?"Resume":"Pause"} subscription</button><button onClick={()=>notify("Cancellation confirmation sent")} className="rounded-xl border border-[#f0d9d6] bg-white py-3 text-xs font-bold text-[#a84b45]">Cancel</button></div></div> }

function ProfileScreen({ go, setAuthenticated }: { go:(s:Screen)=>void; setAuthenticated:(v:boolean)=>void }) { return <div className="space-y-4"><Card className="flex items-center gap-3 p-5"><div className="grid h-14 w-14 place-items-center rounded-full bg-[#d8ebe3] text-base font-bold text-[#1e5b50]">AP</div><div><p className="text-base font-bold">Aarav Kapoor</p><p className="mt-1 text-xs text-[#7c9192]">Flat A-1204 · Tower A</p><p className="mt-1 text-[10px] text-[#398067]">Resident since 2021</p></div></Card><Card className="divide-y divide-[#edf2ef] p-1">{[["Family watch",Shield,()=>go("kids")],["Payment methods",CreditCard,()=>go("payments")],["Notifications",Bell,()=>go("notifications")],["Help & support",MessageCircle,()=>go("notifications")]].map(([label,I,fn])=><button key={label as string} onClick={fn as ()=>void} className="flex w-full items-center gap-3 p-3 text-left"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#edf5f1] text-[#4f8073]"><AppIcon icon={I as IconType} size={16}/></span><span className="flex-1 text-xs font-semibold">{label as string}</span><ChevronRight size={15} className="text-[#9aacab]"/></button>)}</Card><button onClick={()=>setAuthenticated(false)} className="w-full rounded-xl border border-[#efdad6] bg-white py-3 text-xs font-bold text-[#a94b45]">Sign out</button></div> }
function NotificationsScreen({ go, notify }: { go:(s:Screen)=>void; notify:(s:string)=>void }) { const items=[["Payment reminder","Your June maintenance bill is due in 17 days.","10 min ago",Receipt,"amber"],["Visitor arrived","Ananya Mehta has checked in at Tower A gate.","32 min ago",Users,"green"],["Service update","A technician is assigned to SR-2841.","1 hr ago",Wrench,"blue"],["Community notice","Monsoon market registrations are open.","Yesterday",MessageCircle,"slate"]]; return <div className="space-y-2">{items.map(([title,body,time,I,tone])=><Card key={title as string} className="flex gap-3 p-4" onClick={()=>notify(title as string)}><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl ${tone==="amber"?"bg-[#fff0d6] text-[#a16422]":tone==="green"?"bg-[#e0f1e7] text-[#328060]":tone==="blue"?"bg-[#e3eef6] text-[#3d718d]":"bg-[#edf1f1] text-[#607b7c]"}`}><AppIcon icon={I as IconType} size={16}/></span><div className="flex-1"><p className="text-xs font-bold">{title as string}</p><p className="mt-1 text-[11px] leading-relaxed text-[#7d9293]">{body as string}</p><p className="mt-2 text-[10px] text-[#a0adad]">{time as string}</p></div><ChevronRight size={15} className="mt-1 text-[#a0acab]"/></Card>)}<button onClick={()=>go("profile")} className="w-full py-4 text-xs font-bold text-[#397461]">Notification preferences</button></div> }
function SOSScreen({ state, setState, go }: { state:"idle"|"confirm"|"active"; setState:(s:"idle"|"confirm"|"active")=>void; go:(s:Screen)=>void }) { if(state==="active") return <div className="min-h-[100dvh] bg-[#8f2e31] px-6 py-8 text-white"><button onClick={()=>{setState("idle");go("home")}} className="grid h-10 w-10 place-items-center rounded-full bg-white/15"><X size={20}/></button><div className="mt-20 text-center"><div className="mx-auto grid h-24 w-24 place-items-center rounded-full bg-white text-[#a33639]"><Shield size={42}/></div><h1 className="mt-7 text-3xl font-bold">Security is responding</h1><p className="mt-3 text-sm leading-relaxed text-[#f7d8d5]">Willow Creek Security has been alerted to Flat A-1204. A response team is on the way.</p><div className="mt-8 rounded-2xl bg-white/10 p-4 text-left"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-white/15"><Phone size={17}/></span><div><p className="text-xs font-bold">Security desk · +91 22 4890 1100</p><p className="mt-1 text-[10px] text-[#f6ceca]">Connected · estimated response 3 min</p></div></div></div><button onClick={()=>{setState("idle");go("home")}} className="mt-8 w-full rounded-xl bg-white py-3.5 text-xs font-bold text-[#9b3437]">I&apos;m safe · End alert</button></div></div>; return <div className="min-h-[100dvh] bg-[#f6eeec] px-5 py-5"><button onClick={()=>{setState("idle");go("home")}} className="grid h-10 w-10 place-items-center rounded-full bg-white shadow-sm"><ArrowLeft size={19}/></button><div className="mt-12 text-center"><div className="mx-auto grid h-24 w-24 place-items-center rounded-full bg-[#f6dcd9] text-[#b13e3d]"><Shield size={42}/></div><h1 className="mt-7 text-2xl font-bold text-[#532e31]">Need urgent help?</h1><p className="mx-auto mt-3 max-w-[290px] text-sm leading-relaxed text-[#805f60]">This alerts the Willow Creek security desk and shares your flat number for a fast response.</p><Card className="mt-7 p-4 text-left"><div className="flex items-center gap-3"><MapPin size={18} className="text-[#aa4945]"/><div><p className="text-xs font-bold">Alert location</p><p className="mt-1 text-[10px] text-[#839394]">Flat A-1204 · Tower A · Willow Creek</p></div></div></Card><button onClick={()=>setState("active")} className="mt-5 w-full rounded-xl bg-[#ad3d3d] py-4 text-sm font-bold text-white shadow-lg shadow-[#ad3d3d]/20">Alert security now</button><button onClick={()=>{setState("idle");go("home")}} className="mt-3 w-full py-3 text-xs font-bold text-[#8e5c5c]">Cancel</button></div></div> }

function LoginScreen({ onLogin }: { onLogin:()=>void }) { const [otp,setOtp]=useState(false); return otp?<div className="min-h-[100dvh] bg-[#17333a] px-6 py-10 text-white"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-[#d5efdf] text-[#1a725e]"><KeyRound size={22}/></div><p className="mt-12 text-[10px] font-bold uppercase tracking-[.18em] text-[#a9cdbd]">Secure sign in</p><h1 className="mt-3 text-3xl font-bold">Enter your code</h1><p className="mt-3 text-sm leading-relaxed text-[#b6cec7]">We sent a 6-digit code to +91 98••• 3210.</p><input autoFocus maxLength={6} className="mt-8 w-full rounded-xl border border-white/20 bg-white/10 px-4 py-4 text-center text-2xl tracking-[.5em] text-white outline-none" placeholder="••••••" /><button onClick={onLogin} className="mt-5 w-full rounded-xl bg-[#d5efdf] py-3.5 text-xs font-bold text-[#1a5d4d]">Verify & enter</button><button onClick={()=>setOtp(false)} className="mt-5 w-full text-xs text-[#a9cdbd]">Change number</button></div>:<div className="min-h-[100dvh] bg-[#17333a] px-6 py-10 text-white"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-[#d5efdf] text-[#1a725e]"><Home size={26}/></div><p className="mt-16 text-[10px] font-bold uppercase tracking-[.18em] text-[#a9cdbd]">Willow Creek Estates</p><h1 className="mt-3 text-3xl font-bold">Welcome home.</h1><p className="mt-3 text-sm leading-relaxed text-[#b6cec7]">Your calm, connected way to live well inside the community.</p><label className="mt-10 block text-xs font-bold text-[#d3e7df]">Mobile number</label><div className="mt-2 flex rounded-xl border border-white/20 bg-white/10 px-3 py-3.5"><span className="text-sm text-[#b6cec7]">+91</span><input className="ml-3 w-full bg-transparent text-sm outline-none" placeholder="98765 43210"/></div><button onClick={()=>setOtp(true)} className="mt-4 w-full rounded-xl bg-[#d5efdf] py-3.5 text-xs font-bold text-[#1a5d4d]">Send one-time code</button><p className="mt-6 text-center text-[10px] text-[#83a9a0]">By continuing, you agree to the Willow Creek resident terms.</p></div> }

function Field({ label, placeholder }: { label:string; placeholder:string }) { return <div><label className="mb-2 block text-xs font-bold text-[#46666b]">{label}</label><input placeholder={placeholder} className="w-full rounded-xl border border-[#d9e6e0] bg-white px-3 py-3 text-xs text-[#405f62] outline-none placeholder:text-[#a4b0b0] focus:border-[#74b69b]"/></div> }

export default ResidentApp;